# ==============================================================================
# Configuración de Hypridle — Daemon de inactividad para Niri / Wayland
# ==============================================================================

general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = niri msg action power-on-monitors
}

# 1. Bloquear la sesión a los 5 minutos (300 s) de inactividad
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# 2. Apagar las pantallas a los 10 minutos (600 s) de inactividad
listener {
    timeout = 600
    on-timeout = niri msg action power-off-monitors
    on-resume = niri msg action power-on-monitors
}
